name:                chore-select-slack-bot
version:             0.1.0.0
github:              "lehmacdj/chore-select-slack-bot"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/chore-select-slack-bot#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- containers
- time
- network
- scotty
- aeson
- wreq

library:
  source-dirs: src

executables:
  chore-select-slack-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chore-select-slack-bot

tests:
  chore-select-slack-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chore-select-slack-bot
